import { PrismaClient, ProductType, Dietary, FlavorNote, Occasion, GiftOption } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // Create collections
  const premiumCollection = await prisma.collection.upsert({
    where: { slug: 'premium-collection' },
    update: {},
    create: {
      name: 'Premium Collection',
      slug: 'premium-collection',
      description: 'Our finest single-origin and artisanal chocolates',
      image: 'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/premium-collection.jpg',
      featured: true,
    },
  })

  const giftCollection = await prisma.collection.upsert({
    where: { slug: 'gift-collection' },
    update: {},
    create: {
      name: 'Gift Collection',
      slug: 'gift-collection',
      description: 'Perfect gifts for every occasion',
      image: 'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/gift-collection.jpg',
      featured: true,
    },
  })

  const organicCollection = await prisma.collection.upsert({
    where: { slug: 'organic-collection' },
    update: {},
    create: {
      name: 'Organic Collection',
      slug: 'organic-collection',
      description: '100% natural and organic ingredients',
      image: 'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/organic-collection.jpg',
      featured: false,
    },
  })

  // Create ingredients
  const ingredients = await Promise.all([
    prisma.ingredient.upsert({
      where: { name: 'Cocoa Beans' },
      update: {},
      create: {
        name: 'Cocoa Beans',
        description: 'Single-origin cocoa beans from Kerala',
        isNatural: true,
        allergens: [],
      },
    }),
    prisma.ingredient.upsert({
      where: { name: 'Organic Cane Sugar' },
      update: {},
      create: {
        name: 'Organic Cane Sugar',
        description: 'Unrefined organic cane sugar',
        isNatural: true,
        allergens: [],
      },
    }),
    prisma.ingredient.upsert({
      where: { name: 'Vanilla Bean' },
      update: {},
      create: {
        name: 'Vanilla Bean',
        description: 'Madagascar vanilla beans',
        isNatural: true,
        allergens: [],
      },
    }),
    prisma.ingredient.upsert({
      where: { name: 'Himalayan Pink Salt' },
      update: {},
      create: {
        name: 'Himalayan Pink Salt',
        description: 'Pure Himalayan pink salt',
        isNatural: true,
        allergens: [],
      },
    }),
    prisma.ingredient.upsert({
      where: { name: 'Almonds' },
      update: {},
      create: {
        name: 'Almonds',
        description: 'Premium California almonds',
        isNatural: true,
        allergens: ['nuts'],
      },
    }),
  ])

  // Create products
  const products = [
    // Premium Chocolate Bars
    {
      name: 'Single Origin Kerala 70% Dark Chocolate',
      slug: 'single-origin-kerala-70-dark-chocolate',
      description: 'A sophisticated dark chocolate made from single-origin cocoa beans grown in the lush hills of Kerala. This 70% cocoa content bar offers a complex flavor profile with notes of red berries, subtle spice, and a smooth finish.',
      shortDescription: 'Single-origin 70% dark chocolate from Kerala',
      price: 599,
      comparePrice: 699,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/kerala-70-dark.jpg',
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/kerala-70-dark-2.jpg'
      ],
      featured: true,
      inStock: true,
      weight: 100,
      dimensions: '8x4x1',
      cocoaPercentage: 70,
      type: ProductType.BAR,
      packSize: '100g',
      dietary: [Dietary.VEGAN, Dietary.ORGANIC],
      flavorNotes: [FlavorNote.BERRY, FlavorNote.SPICED],
      occasion: [Occasion.CORPORATE, Occasion.FESTIVE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD],
      rating: 4.8,
      reviewCount: 127,
      collectionId: premiumCollection.id,
    },
    {
      name: 'Himalayan Pink Salt Caramel Milk Chocolate',
      slug: 'himalayan-pink-salt-caramel-milk-chocolate',
      description: 'A luxurious milk chocolate bar infused with homemade caramel and finished with a sprinkle of Himalayan pink salt. The perfect balance of sweet and salty creates an unforgettable taste experience.',
      shortDescription: 'Milk chocolate with caramel and Himalayan pink salt',
      price: 449,
      comparePrice: 549,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/pink-salt-caramel.jpg'
      ],
      featured: true,
      inStock: true,
      weight: 85,
      dimensions: '8x4x1',
      cocoaPercentage: 45,
      type: ProductType.BAR,
      packSize: '85g',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.CARAMEL, FlavorNote.VANILLA],
      occasion: [Occasion.BIRTHDAY, Occasion.THANK_YOU],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.RIBBON],
      rating: 4.6,
      reviewCount: 89,
      collectionId: premiumCollection.id,
    },
    {
      name: 'Orange Zest & Almond Dark Chocolate',
      slug: 'orange-zest-almond-dark-chocolate',
      description: 'A sophisticated dark chocolate bar featuring candied orange zest and roasted almonds. The citrus notes perfectly complement the rich cocoa, while the almonds add a satisfying crunch.',
      shortDescription: 'Dark chocolate with orange zest and almonds',
      price: 399,
      comparePrice: 499,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/orange-almond-dark.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 90,
      dimensions: '8x4x1',
      cocoaPercentage: 65,
      type: ProductType.BAR,
      packSize: '90g',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.CITRUS, FlavorNote.NUTTY],
      occasion: [Occasion.ANNIVERSARY, Occasion.CONGRATULATIONS],
      giftOptions: [GiftOption.GIFT_WRAP],
      rating: 4.7,
      reviewCount: 156,
      collectionId: premiumCollection.id,
    },
    {
      name: 'Mint & Dark Chocolate Bar',
      slug: 'mint-dark-chocolate-bar',
      description: 'A refreshing dark chocolate bar infused with natural peppermint oil. The cool mint flavor perfectly balances the rich cocoa, creating a classic combination that never disappoints.',
      shortDescription: 'Dark chocolate with natural mint',
      price: 349,
      comparePrice: 449,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/mint-dark.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 80,
      dimensions: '8x4x1',
      cocoaPercentage: 60,
      type: ProductType.BAR,
      packSize: '80g',
      dietary: [Dietary.VEGAN],
      flavorNotes: [FlavorNote.MINT, FlavorNote.VANILLA],
      occasion: [Occasion.VALENTINE, Occasion.FESTIVE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.BOW],
      rating: 4.5,
      reviewCount: 203,
      collectionId: premiumCollection.id,
    },
    {
      name: 'Coffee & Dark Chocolate Bar',
      slug: 'coffee-dark-chocolate-bar',
      description: 'A bold dark chocolate bar infused with premium Arabica coffee beans. The rich coffee notes enhance the deep cocoa flavors, creating a sophisticated blend for coffee lovers.',
      shortDescription: 'Dark chocolate with Arabica coffee',
      price: 379,
      comparePrice: 479,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/coffee-dark.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 85,
      dimensions: '8x4x1',
      cocoaPercentage: 70,
      type: ProductType.BAR,
      packSize: '85g',
      dietary: [Dietary.VEGAN],
      flavorNotes: [FlavorNote.COFFEE, FlavorNote.NUTTY],
      occasion: [Occasion.CORPORATE, Occasion.FESTIVE],
      giftOptions: [GiftOption.GIFT_WRAP],
      rating: 4.4,
      reviewCount: 78,
      collectionId: premiumCollection.id,
    },

    // Truffles
    {
      name: 'Assorted Chocolate Truffles (12 pieces)',
      slug: 'assorted-chocolate-truffles-12',
      description: 'A luxurious collection of 12 handcrafted chocolate truffles featuring classic flavors like dark chocolate, milk chocolate, and white chocolate. Each truffle is hand-rolled and finished with cocoa powder.',
      shortDescription: '12 handcrafted chocolate truffles',
      price: 899,
      comparePrice: 1099,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/truffles-12.jpg'
      ],
      featured: true,
      inStock: true,
      weight: 180,
      dimensions: '15x10x5',
      cocoaPercentage: 55,
      type: ProductType.TRUFFLE,
      packSize: '12 pieces',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.VANILLA, FlavorNote.CARAMEL],
      occasion: [Occasion.BIRTHDAY, Occasion.ANNIVERSARY, Occasion.VALENTINE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD, GiftOption.RIBBON],
      rating: 4.9,
      reviewCount: 234,
      collectionId: giftCollection.id,
    },
    {
      name: 'Dark Chocolate Sea Salt Truffles (6 pieces)',
      slug: 'dark-chocolate-sea-salt-truffles-6',
      description: 'Six exquisite dark chocolate truffles finished with a sprinkle of sea salt. The perfect balance of rich cocoa and salty notes creates an unforgettable taste experience.',
      shortDescription: '6 dark chocolate truffles with sea salt',
      price: 599,
      comparePrice: 699,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/sea-salt-truffles.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 90,
      dimensions: '12x8x4',
      cocoaPercentage: 70,
      type: ProductType.TRUFFLE,
      packSize: '6 pieces',
      dietary: [Dietary.VEGAN],
      flavorNotes: [FlavorNote.CARAMEL, FlavorNote.VANILLA],
      occasion: [Occasion.THANK_YOU, Occasion.CONGRATULATIONS],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD],
      rating: 4.7,
      reviewCount: 167,
      collectionId: giftCollection.id,
    },

    // Assortments
    {
      name: 'Luxury Chocolate Assortment Box',
      slug: 'luxury-chocolate-assortment-box',
      description: 'A premium collection featuring 24 pieces of our finest chocolates including truffles, pralines, and ganaches. Perfect for gifting or indulging in a variety of flavors.',
      shortDescription: '24-piece luxury chocolate assortment',
      price: 1499,
      comparePrice: 1799,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/luxury-assortment.jpg'
      ],
      featured: true,
      inStock: true,
      weight: 400,
      dimensions: '20x15x8',
      cocoaPercentage: 60,
      type: ProductType.ASSORTMENT,
      packSize: '24 pieces',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.VANILLA, FlavorNote.CARAMEL, FlavorNote.NUTTY, FlavorNote.FRUITY],
      occasion: [Occasion.CORPORATE, Occasion.FESTIVE, Occasion.BIRTHDAY],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD, GiftOption.RIBBON, GiftOption.BOW],
      rating: 4.8,
      reviewCount: 312,
      collectionId: giftCollection.id,
    },
    {
      name: 'Organic Chocolate Sampler',
      slug: 'organic-chocolate-sampler',
      description: 'A curated selection of 16 organic chocolate pieces showcasing different cocoa percentages and flavors. Made with 100% natural ingredients and organic certification.',
      shortDescription: '16-piece organic chocolate sampler',
      price: 799,
      comparePrice: 999,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/organic-sampler.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 200,
      dimensions: '18x12x6',
      cocoaPercentage: 55,
      type: ProductType.ASSORTMENT,
      packSize: '16 pieces',
      dietary: [Dietary.VEGAN, Dietary.ORGANIC],
      flavorNotes: [FlavorNote.VANILLA, FlavorNote.BERRY, FlavorNote.NUTTY],
      occasion: [Occasion.FESTIVE, Occasion.CORPORATE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD],
      rating: 4.6,
      reviewCount: 98,
      collectionId: organicCollection.id,
    },

    // Hampers
    {
      name: 'Premium Chocolate Gift Hamper',
      slug: 'premium-chocolate-gift-hamper',
      description: 'An extravagant gift hamper containing our finest chocolates, artisanal hot chocolate mix, and luxury packaging. Perfect for corporate gifting or special occasions.',
      shortDescription: 'Luxury chocolate gift hamper',
      price: 2499,
      comparePrice: 2999,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/premium-hamper.jpg'
      ],
      featured: true,
      inStock: true,
      weight: 800,
      dimensions: '25x20x12',
      cocoaPercentage: 60,
      type: ProductType.HAMPER,
      packSize: '1 hamper',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.VANILLA, FlavorNote.CARAMEL, FlavorNote.NUTTY],
      occasion: [Occasion.CORPORATE, Occasion.FESTIVE, Occasion.ANNIVERSARY],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD, GiftOption.RIBBON, GiftOption.BOW],
      rating: 4.9,
      reviewCount: 156,
      collectionId: giftCollection.id,
    },
    {
      name: 'Organic Chocolate Wellness Hamper',
      slug: 'organic-chocolate-wellness-hamper',
      description: 'A wellness-focused hamper featuring organic dark chocolates, herbal tea, and wellness accessories. Perfect for health-conscious chocolate lovers.',
      shortDescription: 'Organic wellness chocolate hamper',
      price: 1899,
      comparePrice: 2299,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/wellness-hamper.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 600,
      dimensions: '22x18x10',
      cocoaPercentage: 70,
      type: ProductType.HAMPER,
      packSize: '1 hamper',
      dietary: [Dietary.VEGAN, Dietary.ORGANIC, Dietary.GLUTEN_FREE],
      flavorNotes: [FlavorNote.BERRY, FlavorNote.FLORAL, FlavorNote.SPICED],
      occasion: [Occasion.MOTHERS_DAY, Occasion.FATHERS_DAY, Occasion.THANK_YOU],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD, GiftOption.RIBBON],
      rating: 4.7,
      reviewCount: 89,
      collectionId: organicCollection.id,
    },

    // Gift Boxes
    {
      name: 'Build Your Own Chocolate Box',
      slug: 'build-your-own-chocolate-box',
      description: 'Create your perfect chocolate box by selecting from our wide range of chocolates. Choose from 12, 18, or 24 pieces and customize with your favorite flavors.',
      shortDescription: 'Customizable chocolate box',
      price: 999,
      comparePrice: 1299,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/build-box.jpg'
      ],
      featured: true,
      inStock: true,
      weight: 300,
      dimensions: '18x15x8',
      cocoaPercentage: 60,
      type: ProductType.GIFT_BOX,
      packSize: '12-24 pieces',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.VANILLA, FlavorNote.CARAMEL, FlavorNote.NUTTY, FlavorNote.FRUITY],
      occasion: [Occasion.BIRTHDAY, Occasion.ANNIVERSARY, Occasion.VALENTINE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD, GiftOption.PERSONALIZED_LABEL],
      rating: 4.8,
      reviewCount: 445,
      collectionId: giftCollection.id,
    },
    {
      name: 'Valentine\'s Day Chocolate Box',
      slug: 'valentines-day-chocolate-box',
      description: 'A romantic collection of heart-shaped chocolates and truffles perfect for Valentine\'s Day. Includes special Valentine\'s packaging and a love note.',
      shortDescription: 'Romantic Valentine\'s chocolate box',
      price: 1299,
      comparePrice: 1599,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/valentines-box.jpg'
      ],
      featured: true,
      inStock: true,
      weight: 350,
      dimensions: '20x16x8',
      cocoaPercentage: 55,
      type: ProductType.GIFT_BOX,
      packSize: '18 pieces',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.BERRY, FlavorNote.CARAMEL, FlavorNote.VANILLA],
      occasion: [Occasion.VALENTINE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD, GiftOption.RIBBON, GiftOption.BOW],
      rating: 4.9,
      reviewCount: 278,
      collectionId: giftCollection.id,
    },

    // Hot Chocolate
    {
      name: 'Artisanal Hot Chocolate Mix',
      slug: 'artisanal-hot-chocolate-mix',
      description: 'Premium hot chocolate mix made with real chocolate and natural ingredients. Rich, creamy, and perfect for cozy evenings.',
      shortDescription: 'Premium hot chocolate mix',
      price: 399,
      comparePrice: 499,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/hot-chocolate-mix.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 200,
      dimensions: '12x8x4',
      cocoaPercentage: 65,
      type: ProductType.HOT_CHOCOLATE,
      packSize: '200g',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.VANILLA, FlavorNote.CARAMEL],
      occasion: [Occasion.FESTIVE, Occasion.CORPORATE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD],
      rating: 4.6,
      reviewCount: 134,
      collectionId: premiumCollection.id,
    },
    {
      name: 'Spiced Hot Chocolate Gift Set',
      slug: 'spiced-hot-chocolate-gift-set',
      description: 'A luxurious hot chocolate gift set featuring spiced hot chocolate mix, marshmallows, and a ceramic mug. Perfect for gifting.',
      shortDescription: 'Spiced hot chocolate gift set',
      price: 699,
      comparePrice: 899,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/spiced-hot-chocolate-set.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 500,
      dimensions: '18x15x10',
      cocoaPercentage: 60,
      type: ProductType.HOT_CHOCOLATE,
      packSize: '1 set',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.SPICED, FlavorNote.VANILLA],
      occasion: [Occasion.FESTIVE, Occasion.BIRTHDAY],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD, GiftOption.RIBBON],
      rating: 4.5,
      reviewCount: 67,
      collectionId: giftCollection.id,
    },

    // Spreads
    {
      name: 'Dark Chocolate Hazelnut Spread',
      slug: 'dark-chocolate-hazelnut-spread',
      description: 'A luxurious dark chocolate and hazelnut spread made with premium ingredients. Perfect on toast, pancakes, or as a dessert topping.',
      shortDescription: 'Dark chocolate hazelnut spread',
      price: 299,
      comparePrice: 399,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/chocolate-spread.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 200,
      dimensions: '8x8x6',
      cocoaPercentage: 55,
      type: ProductType.SPREAD,
      packSize: '200g',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.NUTTY, FlavorNote.VANILLA],
      occasion: [Occasion.BREAKFAST, Occasion.BRUNCH],
      giftOptions: [GiftOption.GIFT_WRAP],
      rating: 4.4,
      reviewCount: 89,
      collectionId: premiumCollection.id,
    },

    // More products to reach 25
    {
      name: 'White Chocolate Raspberry Truffles',
      slug: 'white-chocolate-raspberry-truffles',
      description: 'Delicate white chocolate truffles filled with raspberry ganache. A perfect balance of sweet and tart.',
      shortDescription: 'White chocolate raspberry truffles',
      price: 549,
      comparePrice: 649,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/raspberry-truffles.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 120,
      dimensions: '10x8x4',
      cocoaPercentage: 30,
      type: ProductType.TRUFFLE,
      packSize: '8 pieces',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.BERRY, FlavorNote.VANILLA],
      occasion: [Occasion.BIRTHDAY, Occasion.THANK_YOU],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD],
      rating: 4.6,
      reviewCount: 112,
      collectionId: giftCollection.id,
    },
    {
      name: 'Milk Chocolate Caramel Squares',
      slug: 'milk-chocolate-caramel-squares',
      description: 'Smooth milk chocolate squares filled with gooey caramel. A classic combination that never disappoints.',
      shortDescription: 'Milk chocolate caramel squares',
      price: 399,
      comparePrice: 499,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/caramel-squares.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 100,
      dimensions: '12x8x3',
      cocoaPercentage: 40,
      type: ProductType.BAR,
      packSize: '100g',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.CARAMEL, FlavorNote.VANILLA],
      occasion: [Occasion.FESTIVE, Occasion.CORPORATE],
      giftOptions: [GiftOption.GIFT_WRAP],
      rating: 4.5,
      reviewCount: 156,
      collectionId: premiumCollection.id,
    },
    {
      name: 'Dark Chocolate Orange Peel',
      slug: 'dark-chocolate-orange-peel',
      description: 'Candied orange peel dipped in dark chocolate. A sophisticated treat with a perfect balance of citrus and cocoa.',
      shortDescription: 'Dark chocolate orange peel',
      price: 349,
      comparePrice: 449,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/orange-peel.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 80,
      dimensions: '10x6x3',
      cocoaPercentage: 65,
      type: ProductType.BAR,
      packSize: '80g',
      dietary: [Dietary.VEGAN],
      flavorNotes: [FlavorNote.CITRUS, FlavorNote.VANILLA],
      occasion: [Occasion.CORPORATE, Occasion.FESTIVE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD],
      rating: 4.7,
      reviewCount: 98,
      collectionId: premiumCollection.id,
    },
    {
      name: 'Milk Chocolate Almond Clusters',
      slug: 'milk-chocolate-almond-clusters',
      description: 'Premium California almonds coated in smooth milk chocolate. A crunchy and satisfying treat.',
      shortDescription: 'Milk chocolate almond clusters',
      price: 449,
      comparePrice: 549,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/almond-clusters.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 150,
      dimensions: '15x10x4',
      cocoaPercentage: 45,
      type: ProductType.ASSORTMENT,
      packSize: '150g',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.NUTTY, FlavorNote.VANILLA],
      occasion: [Occasion.FESTIVE, Occasion.CORPORATE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.RIBBON],
      rating: 4.6,
      reviewCount: 134,
      collectionId: premiumCollection.id,
    },
    {
      name: 'Dark Chocolate Mint Patties',
      slug: 'dark-chocolate-mint-patties',
      description: 'Refreshing mint patties coated in dark chocolate. A cool and satisfying treat.',
      shortDescription: 'Dark chocolate mint patties',
      price: 379,
      comparePrice: 479,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/mint-patties.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 120,
      dimensions: '12x8x4',
      cocoaPercentage: 60,
      type: ProductType.ASSORTMENT,
      packSize: '120g',
      dietary: [Dietary.VEGAN],
      flavorNotes: [FlavorNote.MINT, FlavorNote.VANILLA],
      occasion: [Occasion.FESTIVE, Occasion.CORPORATE],
      giftOptions: [GiftOption.GIFT_WRAP],
      rating: 4.5,
      reviewCount: 89,
      collectionId: premiumCollection.id,
    },
    {
      name: 'White Chocolate Macadamia Cookies',
      slug: 'white-chocolate-macadamia-cookies',
      description: 'Buttery cookies studded with white chocolate chips and macadamia nuts. A perfect blend of textures and flavors.',
      shortDescription: 'White chocolate macadamia cookies',
      price: 299,
      comparePrice: 399,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/macadamia-cookies.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 200,
      dimensions: '18x12x6',
      cocoaPercentage: 30,
      type: ProductType.ASSORTMENT,
      packSize: '200g',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.NUTTY, FlavorNote.VANILLA],
      occasion: [Occasion.FESTIVE, Occasion.CORPORATE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD],
      rating: 4.4,
      reviewCount: 67,
      collectionId: giftCollection.id,
    },
    {
      name: 'Dark Chocolate Sea Salt Caramels',
      slug: 'dark-chocolate-sea-salt-caramels',
      description: 'Smooth caramel candies coated in dark chocolate and finished with sea salt. A perfect balance of sweet and salty.',
      shortDescription: 'Dark chocolate sea salt caramels',
      price: 449,
      comparePrice: 549,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/sea-salt-caramels.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 100,
      dimensions: '12x8x4',
      cocoaPercentage: 65,
      type: ProductType.ASSORTMENT,
      packSize: '100g',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.CARAMEL, FlavorNote.VANILLA],
      occasion: [Occasion.FESTIVE, Occasion.CORPORATE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.RIBBON],
      rating: 4.6,
      reviewCount: 112,
      collectionId: premiumCollection.id,
    },
    {
      name: 'Milk Chocolate Strawberry Hearts',
      slug: 'milk-chocolate-strawberry-hearts',
      description: 'Delicate heart-shaped chocolates filled with strawberry ganache. Perfect for romantic occasions.',
      shortDescription: 'Milk chocolate strawberry hearts',
      price: 599,
      comparePrice: 699,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/strawberry-hearts.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 120,
      dimensions: '15x10x4',
      cocoaPercentage: 45,
      type: ProductType.TRUFFLE,
      packSize: '12 pieces',
      dietary: [Dietary.VEGETARIAN],
      flavorNotes: [FlavorNote.BERRY, FlavorNote.VANILLA],
      occasion: [Occasion.VALENTINE, Occasion.ANNIVERSARY],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD, GiftOption.RIBBON],
      rating: 4.8,
      reviewCount: 178,
      collectionId: giftCollection.id,
    },
    {
      name: 'Dark Chocolate Espresso Beans',
      slug: 'dark-chocolate-espresso-beans',
      description: 'Coffee beans coated in dark chocolate. A perfect pick-me-up for coffee and chocolate lovers.',
      shortDescription: 'Dark chocolate espresso beans',
      price: 349,
      comparePrice: 449,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/espresso-beans.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 100,
      dimensions: '10x8x4',
      cocoaPercentage: 70,
      type: ProductType.ASSORTMENT,
      packSize: '100g',
      dietary: [Dietary.VEGAN],
      flavorNotes: [FlavorNote.COFFEE, FlavorNote.NUTTY],
      occasion: [Occasion.CORPORATE, Occasion.FESTIVE],
      giftOptions: [GiftOption.GIFT_WRAP],
      rating: 4.5,
      reviewCount: 89,
      collectionId: premiumCollection.id,
    },
    {
      name: 'Organic Dark Chocolate Bark',
      slug: 'organic-dark-chocolate-bark',
      description: 'Organic dark chocolate bark studded with dried fruits and nuts. A healthy and delicious treat.',
      shortDescription: 'Organic dark chocolate bark',
      price: 399,
      comparePrice: 499,
      images: [
        'https://res.cloudinary.com/demo/image/upload/v1/samples/chocolate/chocolate-bark.jpg'
      ],
      featured: false,
      inStock: true,
      weight: 150,
      dimensions: '18x12x3',
      cocoaPercentage: 70,
      type: ProductType.BAR,
      packSize: '150g',
      dietary: [Dietary.VEGAN, Dietary.ORGANIC],
      flavorNotes: [FlavorNote.FRUITY, FlavorNote.NUTTY],
      occasion: [Occasion.FESTIVE, Occasion.CORPORATE],
      giftOptions: [GiftOption.GIFT_WRAP, GiftOption.MESSAGE_CARD],
      rating: 4.6,
      reviewCount: 67,
      collectionId: organicCollection.id,
    },
  ]

  // Create products and connect ingredients
  for (const productData of products) {
    const product = await prisma.product.create({
      data: {
        ...productData,
        ingredients: {
          connect: ingredients.map(ingredient => ({ id: ingredient.id }))
        }
      }
    })

    console.log(`Created product: ${product.name}`)
  }

  console.log('Database seeded successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
